version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: uno
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
